[build]
  command = "pnpm build"
  publish = "public"

[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
